.hound.yml
.rubocop.yml
Gemfile
Gemfile.lock

* Setting the Rubocop version in Hound
* Updating the Rubcop configuration
http://help.houndci.com/en/articles/2461415-supported-linters

Configure Rubocop

---

Gemfile
Gemfile.lock
README.md
intelligent-foods-ruby.gemspec
lib/intelligent_foods.rb
lib/intelligent_foods/api_client.rb
spec/intelligent_foods/api_client_spec.rb
spec/intelligent_foods_spec.rb
spec/spec_helper.rb
spec/support/helpers/api_helper.rb

When using this library, we need to be able to set the data that is
required for connecting to and authenticating with the API.
* Setting the client_id, client_secret, and environment
* Building the correct authentication url
* Instantiating the API Client

Allow the Library to be Configured

---

Gemfile
Gemfile.lock
lib/intelligent_foods.rb
lib/intelligent_foods/api_client.rb
lib/intelligent_foods/resources/menu.rb
spec/intelligent_foods/api_client_spec.rb
spec/intelligent_foods/resources/menu_spec.rb
spec/spec_helper.rb
spec/support/helpers/api_helper.rb

One of the first endpoints that will be accessed is the menus endpoint.
This introduces a Menu resource that can be used to get a listing of
all of the available menus.
* Improving the ApiClient class to handle executing any request
against the API
* Adding the Menu resource with a standard `.all` method

Introduce Menu Resource

---

lib/intelligent_foods.rb

The name of the method was misspelled.
* Fixing the methods spelling.

Fix methods name spelling

---

.github/pull_request_template.md

As a reminder of code quality we want each pull request to have
the same reminder of what a good PR is and to have the same
message structure.
This change addresses that need by:
* Adding PR template to each PR request.

Standardize PR request format

---

lib/intelligent_foods.rb
lib/intelligent_foods/api_client.rb
lib/intelligent_foods/authorization.rb
lib/intelligent_foods/authorization/basic.rb
lib/intelligent_foods/authorization/bearer.rb
spec/intelligent_foods/api_client_spec.rb
spec/support/helpers/api_helper.rb

The methods currently used to authenticate against the partner api does not work. This is due to how the Authorization headers are being set for the authentication API calls. Authentication requires "Basic" auth headers, while Partner API calls require "Bearer" headers.
We should fix the broken APi calls and clean up the authorization logic while we're at it.
* Introducing a BasicAuthorization class
* Introducing a BearerAuthorization class
* Refactoring the ApiClient to make use of the new classes

Improve Partner API Authorization 

---

lib/intelligent_foods.rb
lib/intelligent_foods/api_client.rb
lib/intelligent_foods/errors.rb
lib/intelligent_foods/resources/menu.rb
lib/intelligent_foods/resources/menu_item.rb
lib/intelligent_foods/resources/object.rb
spec/intelligent_foods/resources/menu_spec.rb
spec/support/fixtures/menu_response.json
spec/support/helpers/api_helper.rb

The Intelligent Foods Partner API includes a APi endpoint which returns the Menu along with its associated Menu Items. We'd like to incorporate that API call as a feature of this gem.
* Introducing a new #find method in IntelligentFoods::Menu
* Adding a new resource IntelligentFoods::MenuItem

Introduce Get Menu Functionality

---

lib/intelligent_foods/serializers/order_item_serializer.rb
spec/intelligent_foods/resources/order_spec.rb

Currently, the order item quantity was being set to 1 and not taking
into the quantity that is on the actual order item.
* Updating the OrderItemSerializer to use the order items actual
quantity value

Fix Serialized Order Item Quantity 

---

lib/intelligent_foods/resources/order.rb
lib/intelligent_foods/serializers/recipient_serializer.rb
spec/intelligent_foods/resources/order_spec.rb

If the address value is an empty string, or nil, it should not be included in the request body during order creation. The current version of the Intelligent Foods Partner API raises an error if empty strings are included for any address field.
* Deleting any address keys from the JSON output if blank

Exclude Blank Recipient Address Values

---

lib/intelligent_foods/serializers/order_item_serializer.rb
spec/factories.rb

Instead of using the "id" field to determine the order item, and its
selected protein, we should be utilizing the "sku" fields instead as
those would be externally defined.
* Removing the id and protein_id attributes from the serializer and
replacing them with sku, and protein_sku

Switch to Order Item / Protein Item SKU

---

lib/intelligent_foods/api_client.rb
spec/intelligent_foods/api_client_spec.rb
spec/support/helpers/api_helper.rb

Certain API calls may return a 204 with no response body. If this is the case, we should handle the API response differently and not attempt to parse the body as JSON.
* Refactoring how #execute_request handles responses

Handle 204 Empty Response

---

lib/intelligent_foods/api_client.rb
lib/intelligent_foods/errors.rb
spec/intelligent_foods/api_client_spec.rb

If authentication fails due to a access token timeout, we should capture
this and raise a new error. In addition, we should allow consumers to
check if the client has been authenticated, and if authentication fails
ensure this method returns false.
* Guarding against a 401 (failed authentication) and raising a new error
* Adding a helper method #authenticated?

Handle Authentication Failures

---

lib/intelligent_foods.rb
lib/intelligent_foods/resources/order.rb

Memoizing the api client is causing issues when the client_id and
client_secret are changed from one test to another.
You can reproduce the issue by running this command against commit
5cbe9a9
```
bundle exec rspec './spec/intelligent_foods/resources/order_spec.rb[1:1:5:2]' './spec/intelligent_foods_spec.rb[1:5:1]' --seed 34813 --format d
```
This will produce the following error:
```
IntelligentFoods#client returns an instance of the api client
```
When the api client is set up to fail authentication in a test (i.e.
setting the client_id and client_secret to nil), that client was being
memoized at the class level to the IntelligentFoods class.
When the test for IntelligentFoods#clients was run, it was pulling the
existing client held in memory, rather than the new client that was set
up …

Resolve Issue with Class Level Memoization

---

lib/intelligent_foods.rb
lib/intelligent_foods/api_client.rb
lib/intelligent_foods/errors.rb
lib/intelligent_foods/resources/api_error.rb
lib/intelligent_foods/resources/menu.rb
lib/intelligent_foods/resources/object.rb
lib/intelligent_foods/resources/order.rb
spec/intelligent_foods/api_client_spec.rb
spec/intelligent_foods/resources/menu_spec.rb
spec/support/fixtures/error_response.json
spec/support/helpers/api_helper.rb

The Partner API is changing the response structure of their errors. We should reflect these changes in the Gem to stay at parity.
Link to Partner API error response structure: https://github.com/Intelligent-Foods/partner-api/pull/297
* Introducing a ApiError object class
* Parsing the error response body and parsing the new structure to generate better error messages

Update Error Response Structure

---

lib/intelligent_foods.rb
spec/intelligent_foods_spec.rb

The endpoints for the authentication and apu have recently been simplified. We should update the gem to use the new endpoints, simplifying the configuration logic.
* Updating the endpoints

Update Partner API Endpoints

---

lib/intelligent_foods.rb
spec/intelligent_foods_spec.rb

Previously, a commit was merged which removed the class level memoization of the client. This solved an issue related to specs, but inherently changed how the IntelligentFoods authentication would work. In order to bring back the original authentication flow, and to fix the issues brought up in the original fix
(89d8fa59f74ded904a22f75db93e7b57bd0c50fd) this PR introduces a new method, #refresh_client, which can be used to create a new client object with a new client_id and client_secret.
This fix was tested using the same seed data as per the original commit:
```
bundle exec rspec
'./spec/intelligent_foods/resources/order_spec.rb[1:1:5:2]'
'./spec/intelligent_foods_spec.rb[1:5:1]' --seed 34813 --format d
```
* Introducing a #refresh_client method
* …

Fix Client Instantiation

---

lib/intelligent_foods/resources/order.rb
spec/intelligent_foods/resources/order_spec.rb

The Partner API requires the external id of the order to be of type string. We should force this attribute to be a string to ensure that users don't run into any issues with type validations.
Link to documentation: [Partner API Create Order](https://intelligent-foods.github.io/partner-api/redoc#operation/Create_Order_order_post)
* Stringifying the external id field when building the request body

Stringify Order's External ID

---

lib/intelligent_foods.rb
lib/intelligent_foods/api_client.rb
spec/intelligent_foods/api_client_spec.rb
spec/intelligent_foods_spec.rb

The method in which the Authentication is performed on the new staging environment differs from the existing environment. In order to be able to use the new staging environment we should update the api endpoint url's (for both staging and prod) and update how Authentication is handled. The new staging environment no-longer requires a Basic header to be passed in, but expects a json encoded request body. We should update this Gem to the new authentication requirements, and update the api endpoints as well.
* Updating the endpoints
* Updating how the ApiClient authenticates

Update Partner API Authentication Scheme and API Endpoints

---

lib/intelligent_foods/resources/order.rb
spec/intelligent_foods/resources/order_spec.rb

Currently, the Partner API supports a 'validation_options' request attribute which can be used to skip certain checks, such as temperature and address. We should allow these two fields to be configurable, but defaulted to false.
* Including the validations_options attribute in the request body when creating a order
* Defaulting skip_temperature_check and skip_address_check to false, if the user does not provide an override

Add Validation Options when Creating Orders

---

Gemfile
Gemfile.lock
lib/intelligent_foods/resources/order.rb
spec/factories.rb
spec/intelligent_foods/resources/order_spec.rb
spec/spec_helper.rb
spec/support/api/schemas/order_with_callback.json
spec/support/api_schema_matcher.rb

During order creation, we should include optional params, callback_url and callback_headers. This will allow users to define a callback url which will be sent details of any changes to an order and its shipments.
* Updating the request body to include passed in callback_url and callback_headers

Allow Callback URL and Headers to be Passed In

---

README.md
lib/intelligent_foods/rspec.rb
lib/intelligent_foods/testing/fake.rb

In order to allow customers to test against the gem, we should provide them with a fake. This PR introduces a Testing module which configures Rspec and substitutes a fake in place of the IntelligentFoods gem. Users simply need to include 'inteligent_foods/rspec' in their spec helper.
* Introducing a rspec configuration
* Introducing a Testing module, and a fake

Added RSpec Testing Configuration & Fake

---

lib/intelligent_foods/rspec.rb
lib/intelligent_foods/testing/fake/callback.rb

We should include the default callback response inside of our fake. This will prove useful for users who are testing the webhook feature of the partner api.
* Introducing the default callback request

Include a Default Callback Response
